version: '3'

services:

  vue:
    build:
      context: ./vue
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
    ports:
      - 8080:8080
  react:
    build:
        context: ./react
        dockerfile: Dockerfile
    ports:
      - '8081:8081'
    volumes:
      - .:/app:cached
