version: '3'

services:

  vue:
    build:
      context: ./vue
      dockerfile: Dockerfile
    volumes:
      - ./vue:/app
    ports:
      - 8080:8080
  react:
    build:
        context: ./react
        dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./react:/app:cached
  django:
    build:
      context: ./django
      dockerfile: Dockerfile
    command: 'sh /server/start-django.sh'
    ports:
      - 8000:8000
    volumes:
      - ./django:/server/
    depends_on:
      - postgres
  postgres:
    image: postgres:10.5
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init.d:/docker-entrypoint-initdb.d
      - ./postgres/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"